// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCA-pJXLaduluoqpj83NYsBxaAMEX04d1s',
    appId: '1:622742122019:web:f318a598602005fd888b96',
    messagingSenderId: '622742122019',
    projectId: 'flutter-shop-app-eb7b1',
    authDomain: 'flutter-shop-app-eb7b1.firebaseapp.com',
    storageBucket: 'flutter-shop-app-eb7b1.firebasestorage.app',
    measurementId: 'G-6WXP4TYN2V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCc0TlKp5xOwRDPpB2IzRD987ORfCU037M',
    appId: '1:622742122019:android:0eea728c89f027df888b96',
    messagingSenderId: '622742122019',
    projectId: 'flutter-shop-app-eb7b1',
    storageBucket: 'flutter-shop-app-eb7b1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwUPQe-QQ0358xrC1c580bM1kXOpFzx74',
    appId: '1:622742122019:ios:751302d3e9d3c785888b96',
    messagingSenderId: '622742122019',
    projectId: 'flutter-shop-app-eb7b1',
    storageBucket: 'flutter-shop-app-eb7b1.firebasestorage.app',
    iosBundleId: 'com.example.shopAppNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwUPQe-QQ0358xrC1c580bM1kXOpFzx74',
    appId: '1:622742122019:ios:751302d3e9d3c785888b96',
    messagingSenderId: '622742122019',
    projectId: 'flutter-shop-app-eb7b1',
    storageBucket: 'flutter-shop-app-eb7b1.firebasestorage.app',
    iosBundleId: 'com.example.shopAppNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCA-pJXLaduluoqpj83NYsBxaAMEX04d1s',
    appId: '1:622742122019:web:104e23c645cf27f7888b96',
    messagingSenderId: '622742122019',
    projectId: 'flutter-shop-app-eb7b1',
    authDomain: 'flutter-shop-app-eb7b1.firebaseapp.com',
    storageBucket: 'flutter-shop-app-eb7b1.firebasestorage.app',
    measurementId: 'G-L3BMT9GYLN',
  );

}